### ISSUE TITLE
Omics data sets problem

### ISSUE THREAD

**Issue by abc687** [Aparajita-K/CoALa#1]
How to select Omics data sets on TCGA?How to preprocess data sets？

**Comment by Aparajita-K** [comment]
To browse through the available omics data sets in TCGA, you can look at their GDC data portal at [https://portal.gdc.cancer.gov/](https://portal.gdc.cancer.gov/) and select your cancer multi-omics data set of interest from 33 TCGA projects. Within each project you can select one or more available omics modalities like gene/mRNA expression, DNA methylation, copy number variation and so on. You can download the raw or normalized expression data sets from the GDC portal itself. There are also several other options to download TCGA data in pre-processed [sample x genomic_feature] format. One option is the UCSC Xena browser [https://xenabrowser.net/datapages/](https://xenabrowser.net/datapages/), and another is through the TCGA Biolinks R package [https://bioconductor.org/packages/release/bioc/html/TCGAbiolinks.html](https://bioconductor.org/packages/release/bioc/html/TCGAbiolinks.html). It has a very well documented vignette [https://bioconductor.org/packages/release/bioc/vignettes/TCGAbiolinks/inst/doc/download_prepare.html](https://bioconductor.org/packages/release/bioc/vignettes/TCGAbiolinks/inst/doc/download_prepare.html) that you can follow step by step to prepare and download the pre-processed TCGA data of interest. Hope it helps.
